services:
  - type: static
    name: hydrosync-frontend
    env: static
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
