services:
  - type: web
    name: hydrosync-frontend
    env: node
    plan: free
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
